name: CI

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - master
    tags:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 13.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: |
          yarn install --no-progress --non-interactive --skip-integrity-check
      - name: Check
        run: |
          yarn test
        env:
          CI: true
